name = "StreamGraphs"
uuid = "92555232-c072-11e8-1feb-ad0cb1e67774"
authors = ["azzaare <jeanfrancois.baffier@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
